---
- hosts: all
  become: true
  tasks:
    - name: update Debian
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: update RedHat
      ansible.builtin.yum:
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - ansible.builtin.package:
        name:
          - wrk
        state: present

- hosts: master
  tasks:
    - name: remove whoami service
      command: "docker service rm whoami"
      become: yes
      ignore_errors: True

    - name: create whoami service with 1 replica
      command: "docker service create --name whoami --publish published=8080,target=80 --replicas 1 containous/whoami"
      become: yes

- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Benchmarking with 1 replica
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output_1

    - name: Debug output for 1 replica
      ansible.builtin.debug:
        msg: '{{ wrk_output_1.stdout_lines | select("search", "Req/Sec") | list }}'

# Repeat the process for 2, 4, and 8 replicas
- hosts: master
  tasks:
    - name: remove whoami service
      command: "docker service rm whoami"
      become: yes
      ignore_errors: True

    - name: create whoami service with 2 replicas
      command: "docker service create --name whoami --publish published=8080,target=80 --replicas 2 containous/whoami"
      become: yes

- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Benchmarking with 2 replicas
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output_2

    - name: Debug output for 2 replicas
      ansible.builtin.debug:
        msg: '{{ wrk_output_2.stdout_lines | select("search", "Req/Sec") | list }}'

- hosts: master
  tasks:
    - name: remove whoami service
      command: "docker service rm whoami"
      become: yes
      ignore_errors: True
    - name: create whoami service with 4 replicas
      command: "docker service create --name whoami --publish published=8080,target=80 --replicas 4 containous/whoami"
      become: yes

- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Benchmarking with 4 replicas
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output_4

    - name: Debug output for 4 replicas
      ansible.builtin.debug:
        msg: '{{ wrk_output_4.stdout_lines | select("search", "Req/Sec") | list }}'

- hosts: master
  tasks:
    - name: remove whoami service
      command: "docker service rm whoami"
      become: yes
      ignore_errors: True
    - name: create whoami service with 8 replicas
      command: "docker service create --name whoami --publish published=8080,target=80 --replicas 8 containous/whoami"
      become: yes

- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Benchmarking with 8 replicas
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output_8

    - name: Debug output for 8 replicas
      ansible.builtin.debug:
        msg: '{{ wrk_output_8.stdout_lines | select("search", "Req/Sec") | list }}'
